Repository ATTI-UMC/ATTI-frontend, pull requests merged in 2024-07, with the labels that each got.

#1 docs: PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#5 docs: 파일 구조 정의
  src/api/fetch.jsx
  src/assets/assets
  src/components/Components.jsx
  src/constants/constants.jsx
  src/hooks/useCustom.jsx
  src/pages/SignUp.jsx
  src/store/store.jsx
  src/styles/global.jsx
  src/utils/utils.jsx
Labels: 📃 Docs

#6 chore: 프로젝트 초기 설정 + react router dom
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/index.css
  src/main.jsx
  src/pages/Home.jsx
  src/pages/SignUp.jsx
  src/router.jsx
  src/styles/global.jsx
  src/styles/theme.js
Labels: ✨ Feature, ⚙ Setting

#7 fix: router 오류 수정
  src/App.jsx
  src/router.jsx
Labels: 🐞 BugFix

#8 fix: router export 방식 수정
  src/router.jsx
Labels: 🐞 BugFix

#9 Feature/2 login UI
  src/App.jsx
  src/assets/images/logoAtti.png
  src/assets/images/logoGoogle.png
  src/assets/images/logoKakao.png
  src/assets/images/logoNaver.png
  src/components/LoginFooter.jsx
  src/components/LoginForm.jsx
  src/components/LoginHeader.jsx
  src/main.jsx
  src/pages/Login.jsx
  src/router.jsx
Labels: ✨ Feature, 🎨 Style

#10 Feature/2 login UI 스타일 수정
  src/components/LoginForm.jsx
Labels: 🎨 Style

#11 feat: router 구조 설계
  src/App.jsx
  src/components/LoginFooter.jsx
  src/pages/SignUp.jsx
  src/pages/onboarding/InterestInfo.jsx
  src/pages/onboarding/MbtiInfo.jsx
  src/pages/onboarding/Onboarding.jsx
  src/pages/onboarding/PersonalInfo.jsx
  src/pages/onboarding/TermsAgreement.jsx
  src/pages/signup/Authentication.jsx
  src/pages/signup/PasswordSetup.jsx
  src/pages/signup/SignUp.jsx
  src/router.js
  src/router.jsx
  src/routes/authRoutes.jsx
  src/routes/homeRoutes.jsx
  src/routes/onboardingRoutes.jsx
  src/routes/signupRoutes.jsx
Labels: ✨ Feature

#12 Feature/2 signup email auth UI
  src/assets/images/backBtn.png
  src/assets/images/camera.png
  src/components/signupComponents/Button.jsx
  src/components/signupComponents/ImageUpload.jsx
  src/components/signupComponents/InputField.jsx
  src/components/signupComponents/SignUpHeader.jsx
  src/pages/signup/Authentication.jsx
  src/pages/signup/PasswordSetup.jsx
  src/pages/signup/SignUp.jsx
Labels: ✨ Feature, 🎨 Style

#14 feat : 회원가입 (개인정보, mbti 입력) 창 구현
  src/components/LoginForm.jsx
  src/components/MbtiForm.jsx
  src/components/NextButton.jsx
  src/components/PersonalInfoForm.jsx
  src/pages/onboarding/MbtiInfo.jsx
  src/pages/onboarding/Onboarding.jsx
  src/pages/onboarding/PersonalInfo.jsx
Labels: ✨ Feature, 🎨 Style

#15 docs/2 컴포넌트 폴더 구조 변경
  src/components/login/LoginFooter.jsx
  src/components/login/LoginForm.jsx
  src/components/login/LoginHeader.jsx
  src/components/onboarding/MbtiForm.jsx
  src/components/onboarding/NextButton.jsx
  src/components/onboarding/PersonalInfoForm.jsx
  src/components/signup/Button.jsx
  src/components/signup/ImageUpload.jsx
  src/components/signup/InputField.jsx
  src/components/signup/SignUpHeader.jsx
  src/pages/Login.jsx
  src/pages/onboarding/MbtiInfo.jsx
  src/pages/onboarding/PersonalInfo.jsx
  src/pages/signup/Authentication.jsx
  src/pages/signup/PasswordSetup.jsx
  src/pages/signup/SignUp.jsx
Labels: 📃 Docs

#17 Update .gitignore
  .gitignore
Labels: ⚙ Setting

#18 Feature/home-feature
  .github/workflows/node.js.yml
  src/components/login/LoginFooter.jsx
  src/pages/Debug.jsx
  src/pages/Login.jsx
  src/routes/authRoutes.jsx
  src/routes/homeRoutes.jsx
  src/routes/signupRoutes.jsx
Labels: ✨ Feature

#21 refactor: style 위치 변경
  src/components/Components.jsx
  src/components/login/LoginFooter.jsx
  src/components/login/LoginForm.jsx
  src/components/login/LoginHeader.jsx
  src/components/signup/Button.jsx
  src/components/signup/ImageUpload.jsx
  src/components/signup/InputField.jsx
  src/components/signup/SignUpHeader.jsx
  src/constants/constants.jsx
  src/hooks/useCustom.jsx
  src/pages/Login.jsx
  src/pages/onboarding/MbtiInfo.jsx
  src/pages/onboarding/Onboarding.jsx
  src/pages/onboarding/PersonalInfo.jsx
  src/pages/signup/SignUp.jsx
Labels: 🔨 Refactor

#26 Feature/#2 tag UI
  .github/workflows/node.js.yml
  .github/workspaces/node.js.yml
  src/pages/Debug.jsx
  src/pages/onboarding/InterestInfo.jsx
  src/pages/onboarding/TermsAgreement.jsx
  src/styles/global.jsx
Labels: ✨ Feature, 🎨 Style

#29 Feature/4 password validation
  src/components/signup/Button.jsx
  src/components/signup/InputField.jsx
  src/components/signup/SignUpHeader.jsx
  src/pages/signup/PasswordSetup.jsx
Labels: ✨ Feature

#33 Feature/#16 info validation
  src/components/ProgressBar.jsx
  src/components/onboarding/MbtiContainer.jsx
  src/components/onboarding/MbtiForm.jsx
  src/components/onboarding/NextButton.jsx
  src/components/onboarding/PersonalInfoForm.jsx
  src/pages/onboarding/MbtiInfo.jsx
  src/pages/onboarding/Onboarding.jsx
  src/pages/onboarding/PersonalInfo.jsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Style

#34 Feature/#16 이메일 유효성 검사, 인증번호 전송 및 확인
  src/components/signup/InputField.jsx
  src/pages/signup/Authentication.jsx
  src/pages/signup/PasswordSetup.jsx
Labels: ✨ Feature, 🎨 Style
