Repository ATTI-UMC/ATTI-frontend, pull requests merged in 2024-08, with the labels that each got.

#36 Feature/#16 layout 컴포넌트 추가, 다음버튼 활성화
  src/App.jsx
  src/components/Layout.jsx
  src/components/ProgressBar.jsx
  src/components/onboarding/MbtiForm.jsx
  src/components/onboarding/NextButton.jsx
  src/components/onboarding/PersonalInfoForm.jsx
  src/pages/Home.jsx
  src/pages/onboarding/InterestInfo.jsx
  src/pages/onboarding/Onboarding.jsx
  src/pages/onboarding/TermsAgreement.jsx
  src/store/useOnboardingStore.jsx
Labels: ✨ Feature, 🎨 Style

#37 Feature/#16 onboarding 기능
  src/components/onboarding/InterestInfo/CategoryContent.jsx
  src/components/onboarding/InterestInfo/Content.jsx
  src/components/onboarding/InterestInfo/Header.jsx
  src/components/onboarding/InterestInfo/Tag.jsx
  src/components/onboarding/TermsAgreement/Content.jsx
  src/components/onboarding/TermsAgreement/Header.jsx
  src/components/onboarding/TermsAgreement/Term.jsx
  src/context/TagContext.jsx
  src/context/TermAgreementContext.jsx
  src/pages/onboarding/InterestInfo.jsx
  src/pages/onboarding/TermsAgreement.jsx
Labels: ✨ Feature, 🔨 Refactor

#38 feature/#16-로그인, 학생증 인증 실패 모달 구현
  src/components/Modal.jsx
  src/pages/Login.jsx
  src/pages/signup/Authentication.jsx
Labels: ✨ Feature, 🎨 Style

#35 Feature/#16 학생증 인식 기능 구현
  package-lock.json
  package.json
  src/components/signup/Button.jsx
  src/components/signup/ImageUpload.jsx
  src/components/signup/InputField.jsx
  src/components/signup/SignUpHeader.jsx
  src/pages/signup/Authentication.jsx
  src/pages/signup/SignUp.jsx
Labels: ✨ Feature, 🎨 Style

#44 Feature/31 chat UI
  src/assets/images/INTJ.png
  src/assets/images/button_exit.png
  src/assets/images/button_image.png
  src/assets/images/button_report.png
  src/assets/images/button_send.png
  src/components/chat/BottomSheet.jsx
  src/components/chat/ChatHeader.jsx
  src/components/chat/Info.jsx
  src/components/chat/InputField.jsx
  src/components/chat/MessageItem.jsx
  src/components/chat/MessageList.jsx
  src/components/chat/Modal.jsx
  src/components/chat/TextButton.jsx
  src/components/login/LoginFooter.jsx
  src/components/login/LoginForm.jsx
  src/pages/chat/ChatRoom.jsx
  src/pages/signup/Authentication.jsx
  src/router.js
  src/routes/chatRoomRoutes.jsx
Labels: ✨ Feature, 🎨 Style

#45 Develop 배포
  README.md
  src/assets/images/INTJ.png
  src/assets/images/button_exit.png
  src/assets/images/button_image.png
  src/assets/images/button_report.png
  src/assets/images/button_send.png
  src/components/chat/BottomSheet.jsx
  src/components/chat/ChatHeader.jsx
  src/components/chat/Info.jsx
  src/components/chat/InputField.jsx
  src/components/chat/MessageItem.jsx
  src/components/chat/MessageList.jsx
  src/components/chat/Modal.jsx
  src/components/chat/TextButton.jsx
  src/components/login/LoginFooter.jsx
  src/components/login/LoginForm.jsx
  src/pages/chat/ChatRoom.jsx
  src/pages/signup/Authentication.jsx
  src/router.js
  src/routes/chatRoomRoutes.jsx
Labels: 🌏 Deploy

#46 [Fix] 충돌 해결
  src/pages/Community/CategoryCommunity.jsx
  src/pages/Community/CommunityHome.jsx
  src/pages/Community/Post.jsx
  src/router.js
  src/routes/communityRoutes.jsx
Labels: 🐞 BugFix

#49 Feature/#16 next button activate
  src/components/onboarding/InterestInfo/Content.jsx
  src/components/onboarding/NextButton.jsx
  src/components/onboarding/TermsAgreement/Content.jsx
  src/components/signup/Button.jsx
  src/components/signup/ImageUpload.jsx
  src/pages/onboarding/Onboarding.jsx
  src/pages/signup/Authentication.jsx
  src/pages/signup/PasswordSetup.jsx
Labels: ✨ Feature

#50 [Feature] community 레이아웃, 라우팅
  src/pages/Community/CategoryCommunity.jsx
  src/pages/Community/CommunityHome.jsx
  src/pages/Community/Post.jsx
  src/pages/Community/PostItem.jsx
  src/routes/communityRoutes.jsx
Labels: ✨ Feature, 🎨 Style

#57 Feature/#52 notification UI
  src/assets/images/letter_green.png
  src/assets/images/letter_white.png
  src/components/BottomNav.jsx
  src/components/MainHeader.jsx
  src/components/MainNavigationBar.jsx
  src/components/mypage/Header.jsx
  src/components/notification/Content.jsx
  src/components/notification/NoAlarm.jsx
  src/components/notification/NotificationContainer.jsx
  src/pages/Mypage.jsx
  src/pages/Notification.jsx
  src/pages/chat/ChatMain.jsx
  src/router.jsx
Labels: ✨ Feature, 🎨 Style

#56 Feature/54 sign up email
  src/components/signup/Button.jsx
  src/pages/signup/Authentication.jsx
  src/pages/signup/PasswordSetup.jsx
  src/pages/signup/SignUp.jsx
Labels: ✨ Feature

#58 Feature/19 home main UI
  src/assets/images/book.png
  src/assets/images/medal.png
  src/components/home/Contents.jsx
  src/components/home/Welcome.jsx
  src/pages/Home.jsx
  src/pages/signup/Authentication.jsx
Labels: ✨ Feature
